'use client'

import { useState, useRef, useEffect } from 'react'
import Link from 'next/link'
import ServicePageLayout from '@/components/ServicePageLayout'

const CATEGORIES = [
  {
    id: 'getting-started',
    label: 'Getting Started',
    icon: (
      <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
        <path strokeLinecap="round" strokeLinejoin="round" d="M13 10V3L4 14h7v7l9-11h-7z"/>
      </svg>
    ),
    faqs: [
      {
        q: 'How do I create my account?',
        a: 'Head to the Sign Up page, enter your venue name, type, email and phone number, and create a password. You can also sign up instantly with Google. Once registered you\'ll receive a confirmation email — click the link to verify your account and you\'re in.',
      },
      {
        q: 'How long does it take to get set up?',
        a: 'Most venues are live in under 5 minutes. Add your venue name, upload a logo if you have one, and start building your menu. You don\'t need any technical skills — if you can use a smartphone, you can set up Veno App.',
      },
      {
        q: 'Do I need to install any software?',
        a: 'No. Veno App runs entirely in your browser — on any laptop, tablet, or phone you already own. Your customers also don\'t need to install anything to view your menu or place orders.',
      },
      {
        q: 'What happens after my free trial ends?',
        a: 'You\'ll receive a reminder before your 2-week trial ends. At that point you can choose a plan that fits your venue. If you decide not to continue, your account simply pauses — your data is kept safe for 30 days.',
      },
      {
        q: 'Is a credit card required to start the trial?',
        a: 'No. You can start your free trial with just an email address and phone number — no payment details needed until you decide to subscribe.',
      },
    ],
  },
  {
    id: 'menus',
    label: 'Menus & QR Codes',
    icon: (
      <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
        <path strokeLinecap="round" strokeLinejoin="round" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2"/>
      </svg>
    ),
    faqs: [
      {
        q: 'How do I build my menu?',
        a: 'Go to Menu in your dashboard, create categories (e.g. Starters, Mains, Drinks), then add items with names, descriptions, prices, and photos. Changes go live instantly — no reprinting needed.',
      },
      {
        q: 'How do QR codes work?',
        a: 'Each table or location gets a unique QR code generated by Veno App. When a customer scans it, they see your live menu instantly in their browser — no app download required. You can print, download, or display QR codes however you like.',
      },
      {
        q: 'Can customers order directly from the QR menu?',
        a: 'Yes — if you have the Table Ordering module enabled, customers can browse your menu and place orders straight from their phone. Orders appear on your dashboard in real time.',
      },
      {
        q: 'How do I update my menu?',
        a: 'Any change you make in the dashboard — price updates, new items, mark something as sold out — is reflected live immediately. Customers scanning the QR code always see the latest version.',
      },
    ],
  },
  {
    id: 'orders',
    label: 'Orders & Payments',
    icon: (
      <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
        <path strokeLinecap="round" strokeLinejoin="round" d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z"/>
      </svg>
    ),
    faqs: [
      {
        q: 'How do table orders reach staff?',
        a: 'Orders placed by customers appear instantly in your Orders dashboard. You can set up sound or visual notifications so staff are alerted the moment a new order comes in.',
      },
      {
        q: 'Can I accept payments through Veno App?',
        a: 'Veno App focuses on the ordering and management side. Payment processing is handled by your existing till or card machine — customers pay as normal at the end of their visit or at the counter.',
      },
      {
        q: 'Can I customise what customers can order?',
        a: 'Yes. You can mark items as unavailable, set item options and modifiers (e.g. size, extras, allergies notes), and restrict ordering by time of day.',
      },
      {
        q: 'Is there a limit to how many orders I can receive?',
        a: 'No limits. Veno App handles as many simultaneous orders as your venue needs — whether it\'s 5 tables or 500.',
      },
    ],
  },
  {
    id: 'reservations',
    label: 'Reservations & Bookings',
    icon: (
      <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
        <path strokeLinecap="round" strokeLinejoin="round" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"/>
      </svg>
    ),
    faqs: [
      {
        q: 'Can I take bookings online?',
        a: 'Yes. The Reservations module gives you a booking form you can share as a link or embed on your own website. Customers pick a date, time, and party size, and you get notified instantly.',
      },
      {
        q: 'Can I require a deposit for reservations?',
        a: 'Yes. You can set a deposit amount per booking or per person. Customers pay the deposit online to secure their reservation, and you see the status in your dashboard.',
      },
      {
        q: 'Does the system send booking confirmation to customers?',
        a: 'Yes. Customers automatically receive a confirmation email (and SMS if enabled) when they book, and a reminder before their visit. You can customise the messaging.',
      },
      {
        q: 'Can I block off dates or limit availability?',
        a: 'Yes. You have full control over your availability — set opening hours, close specific dates, and manage walk-ins alongside reservations.',
      },
      {
        q: 'Is the booking system only for restaurants?',
        a: 'Not at all. The Reservations module works for any appointment-based business — beauty salons, barber shops, wellness centres, medical clinics, personal trainers, and more.',
      },
    ],
  },
  {
    id: 'staff',
    label: 'Staff Management',
    icon: (
      <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
        <path strokeLinecap="round" strokeLinejoin="round" d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0z"/>
      </svg>
    ),
    faqs: [
      {
        q: 'How do I add staff members?',
        a: 'Go to Staff in your dashboard and invite team members by email. They\'ll receive an invite to create their own login. You control what each person can access.',
      },
      {
        q: 'Can staff clock in and out through Veno App?',
        a: 'Yes. Staff use the self-service portal to clock in and out at the start and end of their shift. You can see real-time attendance from your manager dashboard.',
      },
      {
        q: 'How does leave management work?',
        a: 'Staff can submit leave requests through their portal with a single tap. You receive the request in your dashboard and can approve or decline it — the staff member is notified automatically.',
      },
      {
        q: 'Can I create and share rotas?',
        a: 'Yes. Build weekly schedules in the rota tool and publish them so staff can see their upcoming shifts. Staff can view their schedule any time through their portal.',
      },
      {
        q: 'Is there a limit to how many staff I can add?',
        a: 'No hard limit — add as many team members as your venue needs. Permissions can be set per person so everyone only sees what\'s relevant to their role.',
      },
    ],
  },
  {
    id: 'analytics',
    label: 'Analytics & Dashboard',
    icon: (
      <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
        <path strokeLinecap="round" strokeLinejoin="round" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z"/>
      </svg>
    ),
    faqs: [
      {
        q: 'What data can I see in my dashboard?',
        a: 'Your dashboard shows live orders, today\'s revenue, upcoming reservations, staff attendance, and low-stock alerts — all in one place. The Analytics section lets you drill into sales trends, best-selling items, peak hours, and customer behaviour over time.',
      },
      {
        q: 'How far back does the analytics data go?',
        a: 'All your data is stored from the moment you start using Veno App. You can filter analytics by day, week, month, or custom date ranges.',
      },
      {
        q: 'Can I export reports?',
        a: 'Yes. Sales and order reports can be exported as CSV for use in spreadsheets or accounting software.',
      },
      {
        q: 'Can multiple managers access the dashboard?',
        a: 'Yes. You can add team members with manager-level access so they can view the dashboard and manage day-to-day operations without having full owner permissions.',
      },
    ],
  },
  {
    id: 'inventory',
    label: 'Inventory',
    icon: (
      <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
        <path strokeLinecap="round" strokeLinejoin="round" d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4"/>
      </svg>
    ),
    faqs: [
      {
        q: 'How does stock tracking work?',
        a: 'You add your ingredients and supplies with quantities and minimum thresholds. As orders come in, the system automatically deducts the right amounts based on your recipes. You always know what you have left.',
      },
      {
        q: 'How do I get low-stock alerts?',
        a: 'Set a minimum quantity for each item. When stock drops to or below that level, you\'ll receive an alert in your dashboard and by notification. You can set different thresholds for different items.',
      },
      {
        q: 'Do I have to update stock manually after every order?',
        a: 'No — that\'s the point. Once you\'ve linked your recipes to your menu items, stock is deducted automatically every time an order is placed. Manual updates are only needed when you receive new deliveries.',
      },
      {
        q: 'Can I record new stock deliveries?',
        a: 'Yes. When a delivery arrives, update the quantities in your inventory and the system adjusts your levels accordingly.',
      },
    ],
  },
  {
    id: 'account',
    label: 'Account & Billing',
    icon: (
      <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
        <path strokeLinecap="round" strokeLinejoin="round" d="M3 10h18M7 15h1m4 0h1m-7 4h12a3 3 0 003-3V8a3 3 0 00-3-3H6a3 3 0 00-3 3v8a3 3 0 003 3z"/>
      </svg>
    ),
    faqs: [
      {
        q: 'How do I change my subscription plan?',
        a: 'Go to Settings → Billing in your dashboard. Veno App is billed per module — there are 3 modules available which you can purchase individually or combine. Adding or removing a module takes effect immediately.',
      },
      {
        q: 'Can I cancel at any time?',
        a: 'Yes. There are no long-term contracts or cancellation fees. Cancel from your dashboard at any time and you\'ll retain access until the end of your current billing period.',
      },
      {
        q: 'How do I update my billing details?',
        a: 'Go to Settings → Billing and update your payment method. Your details are handled securely via Stripe — we never store card information on our servers.',
      },
      {
        q: 'Do you offer refunds?',
        a: 'If you have an issue with a charge, contact us at hello@venoapp.com and we\'ll resolve it. We handle each case fairly and promptly.',
      },
      {
        q: 'Can I get an invoice for my subscription?',
        a: 'Yes. Invoices are generated automatically each billing cycle and are available to download from Settings → Billing.',
      },
    ],
  },
]

function FaqItem({ q, a }) {
  const [open, setOpen] = useState(false)
  const bodyRef = useRef(null)
  const [height, setHeight] = useState(0)

  useEffect(() => {
    if (bodyRef.current) {
      setHeight(open ? bodyRef.current.scrollHeight : 0)
    }
  }, [open])

  return (
    <div className="border-b border-slate-100 dark:border-slate-700 last:border-0">
      <button
        onClick={() => setOpen(!open)}
        className="w-full flex items-center justify-between gap-4 py-5 text-left group"
      >
        <span className="text-slate-900 dark:text-white font-medium text-sm leading-snug group-hover:text-[#6262bd] transition-colors">
          {q}
        </span>
        <span className={`shrink-0 w-6 h-6 rounded-full border-2 flex items-center justify-center transition-all duration-200 ${open ? 'bg-[#6262bd] border-[#6262bd] text-white' : 'border-slate-200 dark:border-slate-600 text-slate-400'}`}>
          <svg className={`w-3 h-3 transition-transform duration-300 ${open ? 'rotate-180' : ''}`} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={3}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M19 9l-7 7-7-7"/>
          </svg>
        </span>
      </button>
      <div
        style={{ height, overflow: 'hidden', transition: 'height 280ms cubic-bezier(0.4,0,0.2,1)' }}
      >
        <p ref={bodyRef} className="pb-5 text-slate-600 dark:text-slate-400 text-sm leading-relaxed pr-8">
          {a}
        </p>
      </div>
    </div>
  )
}

export default function HelpPage() {
  const [activeCategory, setActiveCategory] = useState('getting-started')
  const [search, setSearch] = useState('')

  const activeData = CATEGORIES.find(c => c.id === activeCategory)

  const searchResults = search.trim().length > 1
    ? CATEGORIES.flatMap(cat =>
        cat.faqs
          .filter(f =>
            f.q.toLowerCase().includes(search.toLowerCase()) ||
            f.a.toLowerCase().includes(search.toLowerCase())
          )
          .map(f => ({ ...f, category: cat.label }))
      )
    : null

  return (
    <ServicePageLayout>

      {/* Hero */}
      <section className="relative overflow-hidden py-16 lg:py-24">
        <div className="absolute inset-0 -z-10">
          <div className="absolute top-0 left-1/4 w-96 h-96 bg-[#6262bd]/10 rounded-full blur-3xl"/>
          <div className="absolute bottom-0 right-1/4 w-96 h-96 bg-purple-300/20 rounded-full blur-3xl"/>
        </div>
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center max-w-2xl mx-auto mb-10">
            <div className="inline-block px-4 py-1.5 bg-[#6262bd]/10 rounded-full text-[#6262bd] text-sm font-semibold mb-6">
              Help Centre
            </div>
            <h1 className="text-4xl lg:text-5xl font-bold text-slate-900 dark:text-white mb-5 leading-tight">
              How can we help?
            </h1>
            <p className="text-lg text-slate-600 dark:text-slate-400 leading-relaxed">
              Find answers to common questions about setting up and using Veno App. Can't find what you're looking for? We're just an email away.
            </p>
          </div>

          {/* Search */}
          <div className="max-w-xl mx-auto relative">
            <div className="absolute inset-y-0 left-4 flex items-center pointer-events-none">
              <svg className="w-5 h-5 text-slate-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"/>
              </svg>
            </div>
            <input
              type="text"
              value={search}
              onChange={e => setSearch(e.target.value)}
              placeholder="Search questions…"
              className="w-full pl-12 pr-4 py-4 border-2 border-slate-200 dark:border-slate-600 rounded-2xl bg-white dark:bg-slate-800 text-slate-700 dark:text-slate-200 placeholder:text-slate-400 focus:outline-none focus:border-[#6262bd] text-sm shadow-lg transition-colors"
            />
            {search && (
              <button onClick={() => setSearch('')} className="absolute inset-y-0 right-4 flex items-center text-slate-400 hover:text-slate-600">
                <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12"/>
                </svg>
              </button>
            )}
          </div>
        </div>
      </section>

      {/* FAQ Body */}
      <section className="pb-20 lg:pb-28">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">

          {searchResults ? (
            /* Search results */
            <div className="max-w-3xl mx-auto">
              {searchResults.length === 0 ? (
                <div className="text-center py-16">
                  <div className="w-14 h-14 rounded-full bg-slate-100 dark:bg-slate-800 flex items-center justify-center mx-auto mb-4">
                    <svg className="w-7 h-7 text-slate-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
                      <path strokeLinecap="round" strokeLinejoin="round" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"/>
                    </svg>
                  </div>
                  <p className="text-slate-600 dark:text-slate-400 font-medium mb-2">No results for "{search}"</p>
                  <p className="text-slate-500 dark:text-slate-500 text-sm">Try different keywords or <a href="mailto:hello@venoapp.com" className="text-[#6262bd] hover:underline">email us directly</a>.</p>
                </div>
              ) : (
                <>
                  <p className="text-slate-500 text-sm mb-6">{searchResults.length} result{searchResults.length !== 1 ? 's' : ''} for "{search}"</p>
                  <div className="bg-white dark:bg-slate-800 rounded-2xl border border-slate-100 dark:border-slate-700 px-6 divide-y divide-slate-100 dark:divide-slate-700">
                    {searchResults.map((f, i) => (
                      <div key={i}>
                        <p className="pt-4 pb-1 text-xs font-semibold text-[#6262bd] uppercase tracking-wide">{f.category}</p>
                        <FaqItem q={f.q} a={f.a}/>
                      </div>
                    ))}
                  </div>
                </>
              )}
            </div>
          ) : (
            /* Category browser */
            <div className="flex flex-col lg:flex-row gap-8">

              {/* Sidebar */}
              <div className="lg:w-64 shrink-0">
                <nav className="sticky top-6 space-y-1">
                  {CATEGORIES.map(cat => (
                    <button
                      key={cat.id}
                      onClick={() => setActiveCategory(cat.id)}
                      className={`w-full flex items-center gap-3 px-4 py-3 rounded-xl text-sm font-medium transition-all text-left ${
                        activeCategory === cat.id
                          ? 'bg-[#6262bd] text-white shadow-md shadow-[#6262bd]/20'
                          : 'text-slate-600 dark:text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800 hover:text-slate-900 dark:hover:text-white'
                      }`}
                    >
                      <span className={activeCategory === cat.id ? 'text-white' : 'text-[#6262bd]'}>{cat.icon}</span>
                      {cat.label}
                    </button>
                  ))}
                </nav>
              </div>

              {/* FAQ panel */}
              <div className="flex-1 min-w-0">
                <div className="bg-white dark:bg-slate-800 rounded-2xl border border-slate-100 dark:border-slate-700 px-6 lg:px-8">
                  <div className="flex items-center gap-3 py-6 border-b border-slate-100 dark:border-slate-700 mb-2">
                    <div className="w-9 h-9 rounded-lg bg-[#6262bd]/10 flex items-center justify-center text-[#6262bd]">
                      {activeData.icon}
                    </div>
                    <h2 className="text-lg font-bold text-slate-900 dark:text-white">{activeData.label}</h2>
                    <span className="ml-auto text-xs text-slate-400 font-medium">{activeData.faqs.length} questions</span>
                  </div>
                  {activeData.faqs.map((faq, i) => (
                    <FaqItem key={i} q={faq.q} a={faq.a}/>
                  ))}
                </div>
              </div>
            </div>
          )}
        </div>
      </section>

      {/* Still need help */}
      <section className="py-16 bg-slate-50 dark:bg-slate-800/50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-10">
            <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-3">Still need help?</h2>
            <p className="text-slate-600 dark:text-slate-400">Our team is happy to help with anything — no question is too small.</p>
          </div>
          <div className="grid md:grid-cols-3 gap-6 max-w-4xl mx-auto">
            {[
              {
                icon: <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}><path strokeLinecap="round" strokeLinejoin="round" d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"/></svg>,
                title: 'Email Support',
                desc: 'Send us a message and we\'ll get back to you within one business day.',
                cta: 'hello@venoapp.com',
                href: 'mailto:hello@venoapp.com',
                external: true,
              },
              {
                icon: <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}><path strokeLinecap="round" strokeLinejoin="round" d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z"/></svg>,
                title: 'Contact Form',
                desc: 'Use our contact form to describe your issue and we\'ll follow up directly.',
                cta: 'Go to contact page',
                href: '/contact',
              },
              {
                icon: <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}><path strokeLinecap="round" strokeLinejoin="round" d="M13 10V3L4 14h7v7l9-11h-7z"/></svg>,
                title: 'Start Fresh',
                desc: 'Not a customer yet? Start your free 2-week trial — no card required.',
                cta: 'Start free trial',
                href: '/auth/register',
              },
            ].map(({ icon, title, desc, cta, href, external }) => (
              <div key={title} className="bg-white dark:bg-slate-800 rounded-2xl border border-slate-100 dark:border-slate-700 p-6 flex flex-col">
                <div className="w-11 h-11 rounded-xl bg-[#6262bd]/10 flex items-center justify-center text-[#6262bd] mb-4">{icon}</div>
                <h3 className="font-bold text-slate-900 dark:text-white mb-2">{title}</h3>
                <p className="text-slate-600 dark:text-slate-400 text-sm leading-relaxed mb-4 flex-1">{desc}</p>
                {external
                  ? <a href={href} className="text-sm font-semibold text-[#6262bd] hover:underline">{cta}</a>
                  : <Link href={href} className="text-sm font-semibold text-[#6262bd] hover:underline">{cta} →</Link>
                }
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-16 bg-gradient-to-br from-[#6262bd] to-purple-700">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h2 className="text-3xl font-bold text-white mb-4">Ready to get started?</h2>
          <p className="text-white/80 text-lg mb-8">
            Everything you need to run a smarter venue — in one place, from day one.
          </p>
          <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
            <Link href="/auth/register" className="w-full sm:w-auto bg-white text-[#6262bd] px-8 py-4 rounded-xl font-semibold text-lg hover:bg-slate-100 transition-all">
              Start Free Trial
            </Link>
            <Link href="/contact" className="w-full sm:w-auto border-2 border-white/30 text-white px-8 py-4 rounded-xl font-semibold text-lg hover:bg-white/10 transition-all">
              Talk to Us
            </Link>
          </div>
        </div>
      </section>

    </ServicePageLayout>
  )
}
